# Generated by Django 4.2.16 on 2025-09-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, help_text='Optional username field', max_length=150, null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification email was sent', null=True)),
                ('weekly_goal', models.IntegerField(default=7, help_text='주간 복습 목표 횟수')),
                ('terms_agreed_at', models.DateTimeField(blank=True, help_text='이용약관 동의 일시', null=True)),
                ('privacy_agreed_at', models.DateTimeField(blank=True, help_text='개인정보처리방침 동의 일시', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='문서 제목', max_length=200)),
                ('document_type', models.CharField(choices=[('privacy_policy', '개인정보처리방침'), ('terms_of_service', '이용약관'), ('refund_policy', '환불정책'), ('cookie_policy', '쿠키정책')], help_text='문서 유형', max_length=50, unique=True)),
                ('content', models.TextField(help_text='문서 내용')),
                ('version', models.CharField(default='1.0', help_text='문서 버전', max_length=20)),
                ('effective_date', models.DateTimeField(help_text='시행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
            ],
            options={
                'verbose_name': '법적 문서',
                'verbose_name_plural': '법적 문서들',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], default='free', help_text='Subscription tier', max_length=20)),
                ('max_interval_days', models.IntegerField(default=3, help_text='Maximum review interval in days')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Subscription start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Subscription end date (null for unlimited)', null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for subscription', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('auto_renewal', models.BooleanField(default=True, help_text='Whether to auto-renew subscription')),
                ('next_billing_date', models.DateTimeField(blank=True, help_text='Next automatic billing date', null=True)),
                ('payment_method', models.CharField(blank=True, default='', help_text='Payment method identifier (e.g., CARD-1234)', max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], default='monthly', help_text='Billing cycle frequency', max_length=20)),
                ('next_billing_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Next billing amount', max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'accounts_subscription',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='이메일 알림 전체 활성화/비활성화')),
                ('daily_reminder_enabled', models.BooleanField(default=True, help_text='일일 복습 알림 활성화')),
                ('daily_reminder_time', models.TimeField(default='09:00', help_text='일일 복습 알림 시간')),
                ('evening_reminder_enabled', models.BooleanField(default=True, help_text='저녁 복습 리마인더 활성화')),
                ('evening_reminder_time', models.TimeField(default='20:00', help_text='저녁 복습 리마인더 시간')),
                ('weekly_summary_enabled', models.BooleanField(default=True, help_text='주간 요약 이메일 활성화')),
                ('weekly_summary_day', models.IntegerField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (0, '일요일')], default=1, help_text='주간 요약 발송 요일')),
                ('weekly_summary_time', models.TimeField(default='09:00', help_text='주간 요약 발송 시간')),
                ('unsubscribe_token', models.CharField(blank=True, help_text='이메일 구독 해지용 토큰', max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'accounts_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('ready', '다운로드 준비완료'), ('downloaded', '다운로드 완료'), ('expired', '만료됨')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='생성된 파일 경로', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, help_text='다운로드 링크 만료일', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데이터 내보내기 요청',
                'verbose_name_plural': '데이터 내보내기 요청들',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='삭제 요청 사유')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '처리중'), ('completed', '완료'), ('rejected', '거부')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='관리자 메모')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데이터 삭제 요청',
                'verbose_name_plural': '데이터 삭제 요청들',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='세션 ID (비회원용)', max_length=100)),
                ('essential_cookies', models.BooleanField(default=True, help_text='필수 쿠키 (항상 허용)')),
                ('analytics_cookies', models.BooleanField(default=False, help_text='분석 쿠키')),
                ('marketing_cookies', models.BooleanField(default=False, help_text='마케팅 쿠키')),
                ('functional_cookies', models.BooleanField(default=False, help_text='기능 쿠키')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '쿠키 동의',
                'verbose_name_plural': '쿠키 동의 기록',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', '개인정보처리방침'), ('terms_of_service', '이용약관'), ('marketing', '마케팅 정보 수신'), ('cookies', '쿠키 사용')], max_length=50)),
                ('document_version', models.CharField(help_text='동의한 문서 버전', max_length=20)),
                ('is_consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 동의',
                'verbose_name_plural': '사용자 동의 기록',
                'ordering': ['-consented_at'],
                'unique_together': {('user', 'consent_type', 'document_version')},
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('upgrade', '업그레이드'), ('downgrade', '다운그레이드'), ('cancellation', '구독 취소'), ('renewal', '갱신'), ('initial', '최초 구독'), ('refund', '환불')], help_text='Type of payment or subscription change', max_length=20)),
                ('from_tier', models.CharField(blank=True, choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], help_text='Previous subscription tier', max_length=20, null=True)),
                ('to_tier', models.CharField(choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], help_text='New subscription tier', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Payment amount (0 for free tier)', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund amount for downgrades', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], default='monthly', help_text='Billing cycle for this payment', max_length=20)),
                ('payment_method_used', models.CharField(blank=True, help_text='Payment method used for this transaction', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the payment')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction date and time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'db_table': 'accounts_payment_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_ad9a67_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateTimeField(help_text='Date when billing should occur')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be billed', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], help_text='Billing cycle for this schedule', max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소'), ('prepaid', '선불')], default='pending', help_text='Status of this billing schedule', max_length=20)),
                ('tier_at_billing', models.CharField(choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], help_text='Subscription tier when billing occurs', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method to use for billing', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this billing schedule')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this billing was processed', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedules', to='accounts.subscription')),
            ],
            options={
                'verbose_name': 'Billing Schedule',
                'verbose_name_plural': 'Billing Schedules',
                'db_table': 'accounts_billing_schedule',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['subscription', 'scheduled_date'], name='accounts_bi_subscri_b8a9c1_idx'), models.Index(fields=['status', 'scheduled_date'], name='accounts_bi_status_be1391_idx')],
            },
        ),
    ]
