# Generated by Django 4.2.16 on 2025-11-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymenthistory_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookieconsent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datadeletionrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='datadeletionrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataexportrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='LegalDocument',
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='user',
        ),
        migrations.DeleteModel(
            name='CookieConsent',
        ),
        migrations.DeleteModel(
            name='DataDeletionRequest',
        ),
        migrations.DeleteModel(
            name='DataExportRequest',
        ),
        migrations.DeleteModel(
            name='UserConsent',
        ),
    ]
