# Generated by Django 4.2.7 on 2025-07-22 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic (30일)'), ('premium', 'Premium (60일)'), ('pro', 'Pro (90일)')], default='free', help_text='Subscription tier', max_length=20)),
                ('max_interval_days', models.IntegerField(default=7, help_text='Maximum review interval in days')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Subscription start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Subscription end date (null for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'accounts_subscription',
            },
        ),
    ]
