# Generated by Django 4.2.7 on 2025-07-22 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_subscription_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of usage')),
                ('questions_generated', models.IntegerField(default=0, help_text='Number of AI questions generated on this date')),
                ('evaluations_performed', models.IntegerField(default=0, help_text='Number of AI evaluations performed on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Tracking',
                'verbose_name_plural': 'AI Usage Trackings',
                'db_table': 'accounts_ai_usage_tracking',
                'indexes': [models.Index(fields=['user', 'date'], name='accounts_ai_user_id_03b474_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
