# Generated by Django 4.2.7 on 2025-08-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_goal',
            field=models.IntegerField(default=50, help_text='주간 복습 목표 횟수'),
        ),
    ]
