# Generated by Django 4.2.7 on 2025-08-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_weekly_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_goal',
            field=models.IntegerField(default=7, help_text='주간 복습 목표 횟수'),
        ),
    ]
