# Generated by Django 4.2.7 on 2025-08-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_weekly_goal_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_interval_days',
            field=models.IntegerField(default=3, help_text='Maximum review interval in days'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], default='free', help_text='Subscription tier', max_length=20),
        ),
    ]
