# Generated by Django 4.2.7 on 2025-09-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_enhance_billing_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingschedule',
            new_name='accounts_bi_subscri_b8a9c1_idx',
            old_name='accounts_bi_subscri_1b5e0e_idx',
        ),
        migrations.RenameIndex(
            model_name='billingschedule',
            new_name='accounts_bi_status_be1391_idx',
            old_name='accounts_bi_status_9f2d3c_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='accounts_pa_user_id_ad9a67_idx',
            old_name='accounts_pa_user_id_677502_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for subscription', max_digits=10, null=True),
        ),
    ]
