# Generated by Django 4.2.7 on 2025-09-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_bi_subscri_1b5e0e_idx_accounts_bi_subscri_b8a9c1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for subscription notifications', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the email was subscribed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed', null=True)),
                ('source', models.CharField(default='subscription_page', help_text='Source of the email subscription', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when subscribed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent when subscribed')),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'db_table': 'accounts_email_subscription',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_em_email_05bb81_idx'), models.Index(fields=['is_active', '-subscribed_at'], name='accounts_em_is_acti_76b793_idx')],
            },
        ),
    ]
