# Generated by Django 4.2.7 on 2025-09-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emailsubscription'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS accounts_impersonation_log CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
    ]
