# Generated by Django 4.2.16 on 2025-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20250915_0029'),
    ]

    operations = [
    ]
