# Generated by Django 4.2.16 on 2025-09-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIUsageTracking',
        ),
    ]
