# Generated by Django 4.2.16 on 2025-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_aiusagetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, help_text='개인정보처리방침 동의 일시', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, help_text='이용약관 동의 일시', null=True),
        ),
    ]
