# Generated by Django 4.2.16 on 2025-09-28 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_privacy_agreed_at_user_terms_agreed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='이메일 알림 전체 활성화/비활성화')),
                ('daily_reminder_enabled', models.BooleanField(default=True, help_text='일일 복습 알림 활성화')),
                ('daily_reminder_time', models.TimeField(default='09:00', help_text='일일 복습 알림 시간')),
                ('evening_reminder_enabled', models.BooleanField(default=True, help_text='저녁 복습 리마인더 활성화')),
                ('evening_reminder_time', models.TimeField(default='20:00', help_text='저녁 복습 리마인더 시간')),
                ('weekly_summary_enabled', models.BooleanField(default=True, help_text='주간 요약 이메일 활성화')),
                ('weekly_summary_day', models.IntegerField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (0, '일요일')], default=1, help_text='주간 요약 발송 요일')),
                ('weekly_summary_time', models.TimeField(default='09:00', help_text='주간 요약 발송 시간')),
                ('unsubscribe_token', models.CharField(blank=True, help_text='이메일 구독 해지용 토큰', max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'accounts_notification_preference',
            },
        ),
    ]
