# Generated by Django 4.2.16 on 2025-09-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_notificationpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
