# Generated by Django 4.2.16 on 2025-09-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_emailsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='문서 제목', max_length=200)),
                ('document_type', models.CharField(choices=[('privacy_policy', '개인정보처리방침'), ('terms_of_service', '이용약관'), ('refund_policy', '환불정책'), ('cookie_policy', '쿠키정책')], help_text='문서 유형', max_length=50, unique=True)),
                ('content', models.TextField(help_text='문서 내용')),
                ('version', models.CharField(default='1.0', help_text='문서 버전', max_length=20)),
                ('effective_date', models.DateTimeField(help_text='시행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
            ],
            options={
                'verbose_name': '법적 문서',
                'verbose_name_plural': '법적 문서들',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('ready', '다운로드 준비완료'), ('downloaded', '다운로드 완료'), ('expired', '만료됨')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='생성된 파일 경로', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, help_text='다운로드 링크 만료일', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데이터 내보내기 요청',
                'verbose_name_plural': '데이터 내보내기 요청들',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='삭제 요청 사유')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '처리중'), ('completed', '완료'), ('rejected', '거부')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='관리자 메모')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데이터 삭제 요청',
                'verbose_name_plural': '데이터 삭제 요청들',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='세션 ID (비회원용)', max_length=100)),
                ('essential_cookies', models.BooleanField(default=True, help_text='필수 쿠키 (항상 허용)')),
                ('analytics_cookies', models.BooleanField(default=False, help_text='분석 쿠키')),
                ('marketing_cookies', models.BooleanField(default=False, help_text='마케팅 쿠키')),
                ('functional_cookies', models.BooleanField(default=False, help_text='기능 쿠키')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '쿠키 동의',
                'verbose_name_plural': '쿠키 동의 기록',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', '개인정보처리방침'), ('terms_of_service', '이용약관'), ('marketing', '마케팅 정보 수신'), ('cookies', '쿠키 사용')], max_length=50)),
                ('document_version', models.CharField(help_text='동의한 문서 버전', max_length=20)),
                ('is_consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 동의',
                'verbose_name_plural': '사용자 동의 기록',
                'ordering': ['-consented_at'],
                'unique_together': {('user', 'consent_type', 'document_version')},
            },
        ),
    ]
