# Generated by Django 4.2.7 on 2025-07-22 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_reviewschedule_initial_review_completed'),
        ('content', '0004_remove_tag_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('blur_processing', 'Blur Processing')], help_text='Internal name for the question type', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name for the question type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of how this question type works')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question type is available for generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_question_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The actual question text generated by AI')),
                ('correct_answer', models.TextField(help_text='The correct answer or expected response')),
                ('options', models.JSONField(blank=True, help_text='Multiple choice options (array of strings) or other structured data', null=True)),
                ('difficulty', models.IntegerField(default=1, help_text='Difficulty level from 1 (easy) to 5 (very hard)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation of the correct answer')),
                ('keywords', models.JSONField(blank=True, help_text='Key concepts or terms this question covers', null=True)),
                ('ai_model_used', models.CharField(blank=True, help_text='AI model used to generate this question', max_length=100)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this question (for debugging)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is available for review sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='Content this question is based on', on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='content.content')),
                ('question_type', models.ForeignKey(help_text='Type of question (multiple choice, short answer, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_review.aiquestiontype')),
            ],
            options={
                'db_table': 'ai_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(help_text="The user's answer to the question")),
                ('ai_score', models.FloatField(help_text='AI-generated score from 0.0 (incorrect) to 1.0 (perfect)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('feedback', models.TextField(blank=True, help_text='AI-generated feedback on the answer')),
                ('similarity_score', models.FloatField(blank=True, help_text='Semantic similarity score between user answer and correct answer', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('evaluation_details', models.JSONField(blank=True, help_text='Detailed evaluation breakdown (reasoning, partial scores, etc.)', null=True)),
                ('ai_model_used', models.CharField(blank=True, help_text='AI model used for evaluation', max_length=100)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken for AI evaluation in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Question that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ai_review.aiquestion')),
                ('user', models.ForeignKey(help_text='User who answered the question', on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_generated', models.IntegerField(default=0, help_text='Number of AI questions generated for this session', validators=[django.core.validators.MinValueValidator(0)])),
                ('questions_answered', models.IntegerField(default=0, help_text='Number of questions the user answered', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_score', models.FloatField(blank=True, help_text='Average AI score across all answered questions', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session_duration_seconds', models.IntegerField(blank=True, help_text='Total time spent in the review session', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_processing_time_ms', models.IntegerField(blank=True, help_text='Total time spent on AI processing during the session', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_type', models.CharField(choices=[('traditional', 'Traditional Review'), ('ai_only', 'AI Questions Only'), ('mixed', 'Mixed Traditional + AI')], default='mixed', help_text='Type of review session', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Session notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_history', models.OneToOneField(help_text='Associated traditional review history record', on_delete=django.db.models.deletion.CASCADE, related_name='ai_session', to='review.reviewhistory')),
            ],
            options={
                'db_table': 'ai_review_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_history'], name='ai_review_s_review__ea808c_idx'), models.Index(fields=['created_at'], name='ai_review_s_created_1a203f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiquestion',
            index=models.Index(fields=['content', 'is_active'], name='ai_question_content_f9b4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquestion',
            index=models.Index(fields=['question_type', 'difficulty'], name='ai_question_questio_5444eb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquestion',
            index=models.Index(fields=['created_at'], name='ai_question_created_2e688c_idx'),
        ),
        migrations.AddIndex(
            model_name='aievaluation',
            index=models.Index(fields=['user', 'created_at'], name='ai_evaluati_user_id_f339fe_idx'),
        ),
        migrations.AddIndex(
            model_name='aievaluation',
            index=models.Index(fields=['question', 'ai_score'], name='ai_evaluati_questio_0ca03e_idx'),
        ),
        migrations.AddIndex(
            model_name='aievaluation',
            index=models.Index(fields=['created_at'], name='ai_evaluati_created_5463ef_idx'),
        ),
    ]
