# Generated by Django 4.2.7 on 2025-07-22 09:19

from django.db import migrations


def create_default_question_types(apps, schema_editor):
    """Create default AI question types"""
    AIQuestionType = apps.get_model('ai_review', 'AIQuestionType')
    
    question_types = [
        {
            'name': 'multiple_choice',
            'display_name': 'Multiple Choice',
            'description': 'Generate multiple choice questions with 4 options',
            'is_active': True
        },
        {
            'name': 'short_answer',
            'display_name': 'Short Answer',
            'description': 'Generate open-ended questions requiring text responses',
            'is_active': True
        },
        {
            'name': 'fill_blank',
            'display_name': 'Fill in the Blank',
            'description': 'Generate questions with key terms removed for filling',
            'is_active': True
        },
        {
            'name': 'blur_processing',
            'display_name': 'Blur Processing',
            'description': 'Identify key concepts to blur in content for interactive review',
            'is_active': True
        }
    ]
    
    for question_type_data in question_types:
        AIQuestionType.objects.get_or_create(
            name=question_type_data['name'],
            defaults=question_type_data
        )


def remove_default_question_types(apps, schema_editor):
    """Remove default AI question types"""
    AIQuestionType = apps.get_model('ai_review', 'AIQuestionType')
    question_type_names = ['multiple_choice', 'short_answer', 'fill_blank', 'blur_processing']
    AIQuestionType.objects.filter(name__in=question_type_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_question_types,
            remove_default_question_types
        ),
    ]
