# Generated by Django manually for performance optimization

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review', '0001_initial'),
    ]

    operations = [
        # AIQuestion indexes for fast lookups
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ai_question_content_active_idx ON ai_questions(content_id, is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS ai_question_content_active_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ai_question_type_difficulty_idx ON ai_questions(question_type_id, difficulty);",
            reverse_sql="DROP INDEX IF EXISTS ai_question_type_difficulty_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ai_question_created_idx ON ai_questions(created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS ai_question_created_idx;"
        ),
    ]