# Generated by Django 4.2.7 on 2025-07-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review', '0002_add_performance_indexes'),
        ('ai_review', '0002_auto_20250722_1819'),
    ]

    operations = [
    ]
