# Generated by Django 4.2.7 on 2025-07-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review', '0003_merge_20250723_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestiontype',
            name='name',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('blur_processing', 'Blur Processing')], help_text='Internal name for the question type', max_length=50, unique=True),
        ),
    ]
