# Generated by Django 4.2.7 on 2025-08-17 22:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_merge_20250723_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_review', '0004_alter_aiquestiontype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='주간 시작일 (월요일)')),
                ('week_end_date', models.DateField(help_text='주간 종료일 (일요일)')),
                ('total_questions', models.IntegerField(default=15, help_text='총 문제 수', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('completed_questions', models.IntegerField(default=0, help_text='완료한 문제 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('correct_answers', models.IntegerField(default=0, help_text='정답 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.FloatField(blank=True, help_text='최종 점수 (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('time_limit_minutes', models.IntegerField(choices=[(30, '30분'), (60, '60분'), (0, '무제한')], default=30, help_text='시험 시간 제한')),
                ('started_at', models.DateTimeField(blank=True, help_text='시험 시작 시간', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='시험 완료 시간', null=True)),
                ('difficulty_distribution', models.JSONField(default=dict, help_text="난이도별 문제 분포 {'easy': 5, 'medium': 8, 'hard': 2}")),
                ('content_coverage', models.JSONField(default=list, help_text='포함된 콘텐츠 ID 목록')),
                ('weak_areas', models.JSONField(default=list, help_text='취약 분야 분석 결과')),
                ('improvement_from_last_week', models.FloatField(blank=True, help_text='지난 주 대비 향상도 (%)', null=True)),
                ('status', models.CharField(choices=[('draft', '준비중'), ('ready', '시작가능'), ('in_progress', '진행중'), ('completed', '완료'), ('expired', '만료')], default='draft', help_text='시험 상태', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='시험을 본 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_weekly_tests',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간'), ('quarterly', '분기')], help_text='분석 기간 유형', max_length=20)),
                ('period_start', models.DateField(help_text='분석 시작일')),
                ('period_end', models.DateField(help_text='분석 종료일')),
                ('total_study_minutes', models.IntegerField(default=0, help_text='총 학습 시간 (분)')),
                ('average_daily_minutes', models.FloatField(default=0.0, help_text='일 평균 학습 시간 (분)')),
                ('peak_study_hour', models.IntegerField(blank=True, help_text='가장 집중도 높은 시간대 (0-23시)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('study_day_pattern', models.JSONField(default=dict, help_text="요일별 학습 패턴 {'mon': 30, 'tue': 45, ...}")),
                ('total_contents_studied', models.IntegerField(default=0, help_text='학습한 콘텐츠 수')),
                ('total_reviews_completed', models.IntegerField(default=0, help_text='완료한 복습 수')),
                ('average_accuracy', models.FloatField(default=0.0, help_text='평균 정답률 (%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('weak_categories', models.JSONField(default=list, help_text="취약 카테고리 목록 [{'category': 'math', 'score': 65}, ...]")),
                ('strong_categories', models.JSONField(default=list, help_text='강점 카테고리 목록')),
                ('recommended_focus_areas', models.JSONField(default=list, help_text='AI 추천 집중 학습 분야')),
                ('personalized_tips', models.JSONField(default=list, help_text='개인화된 학습 팁')),
                ('predicted_improvement_areas', models.JSONField(default=list, help_text='예상 개선 가능 분야')),
                ('efficiency_score', models.FloatField(default=0.0, help_text='학습 효율성 점수', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('retention_rate', models.FloatField(default=0.0, help_text='기억 유지율', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='분석 대상 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_learning_analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='InstantContentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point', models.CharField(help_text='검토 시점 (예: 50%, 완료 등)', max_length=50)),
                ('questions_count', models.IntegerField(default=3, help_text='생성된 문제 수', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('correct_count', models.IntegerField(default=0, help_text='정답 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('understanding_score', models.FloatField(help_text='이해도 점수 (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('weak_points', models.JSONField(default=list, help_text='취약점 목록')),
                ('feedback', models.TextField(blank=True, help_text='AI 생성 피드백')),
                ('duration_seconds', models.IntegerField(help_text='검토 소요 시간 (초)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='검토 대상 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='instant_checks', to='content.content')),
                ('user', models.ForeignKey(help_text='검토를 수행한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='instant_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_instant_content_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWrongAnswerClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(help_text='사용자의 오답')),
                ('correct_answer', models.TextField(help_text='정답')),
                ('error_analysis', models.TextField(help_text='오답 원인 분석')),
                ('concept_explanation', models.TextField(help_text='핵심 개념 재설명')),
                ('additional_tips', models.JSONField(default=list, help_text='추가 학습 팁')),
                ('practice_question', models.JSONField(blank=True, help_text='연습 문제', null=True)),
                ('improvement_score', models.FloatField(blank=True, help_text='재시도 후 향상도', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='문제 해결 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_question', models.ForeignKey(help_text='원본 문제', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_sessions', to='ai_review.aiquestion')),
                ('user', models.ForeignKey(help_text='질문한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_wrong_answer_clinics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISummaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('one_page', '1페이지 요약'), ('mind_map', '마인드맵'), ('key_points', '핵심 포인트'), ('cornell_notes', '코넬 노트')], default='one_page', help_text='요약 형식', max_length=30)),
                ('summary_content', models.TextField(help_text='요약 내용')),
                ('key_concepts', models.JSONField(default=list, help_text='핵심 개념 목록')),
                ('important_terms', models.JSONField(default=list, help_text='중요 용어 및 정의')),
                ('visual_elements', models.JSONField(default=dict, help_text='시각적 요소 (다이어그램, 차트 등)')),
                ('study_questions', models.JSONField(default=list, help_text='학습 확인 질문')),
                ('pdf_url', models.URLField(blank=True, help_text='생성된 PDF 파일 URL')),
                ('word_count', models.IntegerField(default=0, help_text='요약 단어 수')),
                ('compression_ratio', models.FloatField(default=0.0, help_text='압축률 (원본 대비 요약 비율)')),
                ('ai_model_used', models.CharField(blank=True, help_text='사용된 AI 모델', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='원본 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='content.content')),
                ('user', models.ForeignKey(help_text='요청한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_summary_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIStudyMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('guided_learning', '가이드 학습'), ('hint_system', '힌트 시스템'), ('error_analysis', '오답 분석'), ('concept_explanation', '개념 설명')], help_text='세션 유형', max_length=30)),
                ('interaction_count', models.IntegerField(default=0, help_text='상호작용 횟수')),
                ('hints_provided', models.JSONField(default=list, help_text='제공된 힌트 목록')),
                ('user_level', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='intermediate', help_text='감지된 사용자 수준', max_length=20)),
                ('adapted_explanations', models.JSONField(default=list, help_text='수준별 맞춤 설명')),
                ('learning_progress', models.JSONField(default=dict, help_text='학습 진행 상황 추적')),
                ('session_duration_minutes', models.IntegerField(default=0, help_text='세션 지속 시간 (분)')),
                ('effectiveness_score', models.FloatField(blank=True, help_text='세션 효과성 점수', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='세션 시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, help_text='세션 종료 시간', null=True)),
                ('content', models.ForeignKey(help_text='학습 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='study_mate_sessions', to='content.content')),
                ('user', models.ForeignKey(help_text='학습자', on_delete=django.db.models.deletion.CASCADE, related_name='study_mate_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_study_mate_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestionTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_type', models.CharField(choices=[('reverse', '역질문'), ('practical', '실생활 적용'), ('comparison', '비교형'), ('troubleshoot', '문제해결형'), ('analogy', '비유/예시'), ('step_by_step', '단계별 풀이')], help_text='변형 방식', max_length=30)),
                ('transformed_question_text', models.TextField(help_text='변형된 문제')),
                ('transformed_answer', models.TextField(help_text='변형 문제 답안')),
                ('transformation_explanation', models.TextField(blank=True, help_text='변형 의도 설명')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], help_text='사용자 평점 (1-5)', null=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='도움되었는지 여부', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_question', models.ForeignKey(help_text='원본 문제', on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='ai_review.aiquestion')),
                ('user', models.ForeignKey(help_text='변형을 요청한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='question_transformations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_question_transformers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAdaptiveDifficultyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_area', models.CharField(help_text='시험 범위 (카테고리 또는 콘텐츠 그룹)', max_length=100)),
                ('target_questions', models.IntegerField(default=10, help_text='목표 문제 수')),
                ('current_difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', help_text='현재 난이도', max_length=20)),
                ('consecutive_correct', models.IntegerField(default=0, help_text='연속 정답 수')),
                ('consecutive_wrong', models.IntegerField(default=0, help_text='연속 오답 수')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('final_difficulty_level', models.CharField(blank=True, max_length=20)),
                ('estimated_proficiency', models.FloatField(blank=True, help_text='추정 숙련도 (0-100)', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='시험 응시자', on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_adaptive_difficulty_tests',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='문제 순서')),
                ('user_answer', models.TextField(blank=True, help_text='사용자 답변')),
                ('is_correct', models.BooleanField(blank=True, help_text='정답 여부', null=True)),
                ('ai_score', models.FloatField(blank=True, help_text='AI 평가 점수', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('time_spent_seconds', models.IntegerField(blank=True, help_text='문제 풀이 시간 (초)', null=True)),
                ('answered_at', models.DateTimeField(blank=True, help_text='답변 제출 시간', null=True)),
                ('ai_question', models.ForeignKey(help_text='AI 생성 문제', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_test_uses', to='ai_review.aiquestion')),
                ('weekly_test', models.ForeignKey(help_text='소속 주간 시험', on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='ai_review.weeklytest')),
            ],
            options={
                'db_table': 'ai_weekly_test_questions',
                'ordering': ['order'],
                'unique_together': {('weekly_test', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='weeklytest',
            index=models.Index(fields=['user', 'week_start_date'], name='ai_weekly_t_user_id_0c175b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklytest',
            index=models.Index(fields=['status', 'created_at'], name='ai_weekly_t_status_a07b27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytest',
            unique_together={('user', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='learninganalytics',
            index=models.Index(fields=['user', 'period_type', 'period_start'], name='ai_learning_user_id_af2449_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together={('user', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='instantcontentcheck',
            index=models.Index(fields=['user', 'content', 'created_at'], name='ai_instant__user_id_9d3d56_idx'),
        ),
        migrations.AddIndex(
            model_name='aiwronganswerclinic',
            index=models.Index(fields=['user', 'created_at'], name='ai_wrong_an_user_id_cbfea2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiwronganswerclinic',
            index=models.Index(fields=['original_question', 'is_resolved'], name='ai_wrong_an_origina_580102_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummarynote',
            index=models.Index(fields=['content', 'user', 'created_at'], name='ai_summary__content_6650e8_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummarynote',
            index=models.Index(fields=['summary_type', 'created_at'], name='ai_summary__summary_8683d8_idx'),
        ),
        migrations.AddIndex(
            model_name='aistudymate',
            index=models.Index(fields=['user', 'content', 'started_at'], name='ai_study_ma_user_id_56ba16_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquestiontransformer',
            index=models.Index(fields=['user', 'transformation_type'], name='ai_question_user_id_d1307c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquestiontransformer',
            index=models.Index(fields=['original_question', 'created_at'], name='ai_question_origina_14d5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='aiadaptivedifficultytest',
            index=models.Index(fields=['user', 'started_at'], name='ai_adaptive_user_id_95c4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiadaptivedifficultytest',
            index=models.Index(fields=['content_area', 'completed_at'], name='ai_adaptive_content_8a09f0_idx'),
        ),
    ]
