# Generated by Django 4.2.7 on 2025-09-04 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_category_updated_at'),
        ('ai_review', '0005_weeklytest_learninganalytics_instantcontentcheck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiadaptivedifficultytest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learninganalytics',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='weeklytest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='weeklytest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='adaptive_mode',
            field=models.BooleanField(default=True, help_text='적응형 모드 활성화'),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='선택한 카테고리 (None이면 전체 콘텐츠)', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='consecutive_correct',
            field=models.IntegerField(default=0, help_text='연속 정답 수'),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='consecutive_wrong',
            field=models.IntegerField(default=0, help_text='연속 오답 수'),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='current_difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', help_text='현재 난이도', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='estimated_proficiency',
            field=models.FloatField(blank=True, help_text='추정 숙련도 (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='weeklytest',
            name='question_type_distribution',
            field=models.JSONField(default=dict, help_text="문제 유형별 분배 {'multiple_choice': 6, 'short_answer': 3, 'essay': 1}"),
        ),
        migrations.AlterField(
            model_name='weeklytest',
            name='total_questions',
            field=models.IntegerField(default=10, help_text='총 문제 수', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytest',
            unique_together={('user', 'category', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='weeklytest',
            index=models.Index(fields=['user', 'category'], name='ai_weekly_t_user_id_47fdb3_idx'),
        ),
        migrations.DeleteModel(
            name='AIAdaptiveDifficultyTest',
        ),
        migrations.DeleteModel(
            name='LearningAnalytics',
        ),
    ]
