# Generated by Django 4.2.7 on 2025-09-04 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_review', '0006_remove_aiadaptivedifficultytest_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUnderstandingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_count', models.IntegerField(default=3, help_text='생성된 문제 수', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('correct_count', models.IntegerField(default=0, help_text='정답 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('understanding_score', models.FloatField(help_text='이해도 점수 (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('weak_points', models.JSONField(default=list, help_text='취약점 목록')),
                ('feedback', models.TextField(blank=True, help_text='AI 생성 피드백')),
                ('duration_seconds', models.IntegerField(help_text='검사 소요 시간 (초)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='검사 대상 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='understanding_checks', to='content.content')),
                ('user', models.ForeignKey(help_text='검사를 받은 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='understanding_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_content_understanding_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='aistudymate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aistudymate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aisummarynote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aisummarynote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aiwronganswerclinic',
            name='original_question',
        ),
        migrations.RemoveField(
            model_name='aiwronganswerclinic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instantcontentcheck',
            name='content',
        ),
        migrations.RemoveField(
            model_name='instantcontentcheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIQuestionTransformer',
        ),
        migrations.DeleteModel(
            name='AIStudyMate',
        ),
        migrations.DeleteModel(
            name='AISummaryNote',
        ),
        migrations.DeleteModel(
            name='AIWrongAnswerClinic',
        ),
        migrations.DeleteModel(
            name='InstantContentCheck',
        ),
        migrations.AddIndex(
            model_name='contentunderstandingcheck',
            index=models.Index(fields=['user', 'content', 'created_at'], name='ai_content__user_id_f70dcc_idx'),
        ),
    ]
