# Generated by Django manually for performance optimization

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        # Content model indexes for common query patterns
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_author_created_idx ON content_content(author_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_author_created_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_author_category_idx ON content_content(author_id, category_id);",
            reverse_sql="DROP INDEX IF EXISTS content_author_category_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_author_priority_idx ON content_content(author_id, priority);",
            reverse_sql="DROP INDEX IF EXISTS content_author_priority_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_category_slug_idx ON content_category(slug);",
            reverse_sql="DROP INDEX IF EXISTS content_category_slug_idx;"  
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_category_user_idx ON content_category(user_id) WHERE user_id IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS content_category_user_idx;"
        ),
        
        # Full-text search index for content (PostgreSQL specific)
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS content_search_idx ON content_content 
            USING gin(to_tsvector('simple', title || ' ' || content));
            """,
            reverse_sql="DROP INDEX IF EXISTS content_search_idx;"
        ),
    ]