# Generated by Django 4.2.16 on 2025-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='review_mode',
            field=models.CharField(choices=[('objective', '객관식 (내용 보고 기억함/모름 선택)'), ('subjective', '주관식 (먼저 작성 후 AI 자동 평가)')], default='objective', help_text='Review test mode: objective or subjective with AI auto-evaluation', max_length=20),
        ),
    ]
