# Generated by Django 4.2.7 on 2025-07-15 05:32

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default categories"""
    from django.utils.text import slugify
    Category = apps.get_model('content', 'Category')
    
    default_categories = [
        {'name': '영어', 'slug': 'english', 'description': '영어 학습 콘텐츠'},
        {'name': '수학', 'slug': 'mathematics', 'description': '수학 학습 콘텐츠'},
        {'name': '경제', 'slug': 'economics', 'description': '경제학 관련 콘텐츠'},
        {'name': '프로그래밍', 'slug': 'programming', 'description': '프로그래밍 및 개발 관련'},
        {'name': '일반', 'slug': 'general', 'description': '기타 학습 콘텐츠'},
    ]
    
    for category_data in default_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={
                'slug': category_data['slug'],
                'description': category_data['description']
            }
        )


def reverse_create_default_categories(apps, schema_editor):
    """Remove default categories"""
    Category = apps.get_model('content', 'Category')
    default_names = ['영어', '수학', '경제', '프로그래밍', '일반']
    Category.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            reverse_create_default_categories
        ),
    ]
