# Generated by Django 4.2.16 on 2025-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_ai_validated_at_content_ai_validation_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mc_choices',
            field=models.JSONField(blank=True, help_text='Multiple choice options (AI generated): {"choices": [...], "correct_answer": "..."}', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='review_mode',
            field=models.CharField(choices=[('objective', '기억 확인 (제목만 보고 기억함/모름 선택)'), ('descriptive', '서술형 (제목 보고 내용 작성 → AI 평가)'), ('multiple_choice', '객관식 (내용 보고 4지선다에서 제목 맞추기)'), ('subjective', '주관식 (내용 보고 제목 유추 작성 → AI 평가)')], default='objective', help_text='Review test mode: objective or subjective with AI auto-evaluation', max_length=20),
        ),
    ]
