# Generated by Django 4.2.16 on 2025-11-18 09:17

from django.db import migrations


def convert_deprecated_review_modes(apps, schema_editor):
    """Convert only subjective mode to objective mode. Keep descriptive mode."""
    Content = apps.get_model('content', 'Content')

    # Convert only subjective to objective
    subjective_count = Content.objects.filter(review_mode='subjective').update(review_mode='objective')

    print(f"Migration: Converted {subjective_count} subjective content to objective mode")


def reverse_migration(apps, schema_editor):
    """Reverse migration - no-op as we can't know which mode to revert to."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_mc_choices_alter_content_review_mode'),
    ]

    operations = [
        migrations.RunPython(convert_deprecated_review_modes, reverse_migration),
    ]
