# Generated by Django 4.2.7 on 2025-07-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_performance_indexes'),
        ('content', '0004_remove_tag_model'),
    ]

    operations = [
    ]
