# Generated by Django 4.2.16 on 2025-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_convert_subjective_descriptive_to_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ai_validated_at',
            field=models.DateTimeField(blank=True, help_text='AI validation completion timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='ai_validation_result',
            field=models.JSONField(blank=True, help_text='AI validation detailed result (factual_accuracy, logical_consistency, title_relevance)', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='ai_validation_score',
            field=models.FloatField(blank=True, help_text='AI validation average score (0-100, average of 3 metrics)', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_ai_validated',
            field=models.BooleanField(default=False, help_text='Whether AI validation is completed (required for exam generation)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='review_mode',
            field=models.CharField(choices=[('objective', '기억 확인 (제목만 보고 기억함/모름 선택)'), ('descriptive', '서술형 (제목 보고 내용 작성 후 AI 평가)'), ('multiple_choice', '객관식 (내용 보고 4지선다에서 제목 맞추기)')], default='objective', help_text='Review test mode: objective or subjective with AI auto-evaluation', max_length=20),
        ),
    ]
