# Generated by Django 4.2.7 on 2025-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_merge_20250723_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
