# Generated by Django 4.2.7 on 2025-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author', '-created_at'], name='content_author_created'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author', 'category', '-created_at'], name='content_auth_cat_created'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', '-created_at'], name='content_category_created'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['priority', '-created_at'], name='content_priority_created'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='category_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='content_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(check=models.Q(('content', ''), _negated=True), name='content_body_not_empty'),
        ),
    ]
