# Generated by Django 4.2.16 on 2025-09-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_priority_created',
        ),
        migrations.RemoveField(
            model_name='content',
            name='priority',
        ),
    ]
