# Generated by Django 4.2.7 on 2025-09-04 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUsageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_daily', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('churned_users', models.IntegerField(default=0)),
                ('free_users', models.IntegerField(default=0)),
                ('basic_users', models.IntegerField(default=0)),
                ('pro_users', models.IntegerField(default=0)),
                ('subscription_revenue_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_content_created', models.IntegerField(default=0)),
                ('total_reviews_completed', models.IntegerField(default=0)),
                ('average_success_rate', models.FloatField(default=0.0)),
                ('ai_questions_generated', models.IntegerField(default=0)),
                ('ai_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('ai_tokens_used', models.BigIntegerField(default=0)),
                ('average_api_response_time_ms', models.IntegerField(default=0)),
                ('error_rate_percentage', models.FloatField(default=0.0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bi_system_usage_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], default='FREE', max_length=20)),
                ('tier_start_date', models.DateTimeField()),
                ('tier_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_content_created', models.IntegerField(default=0)),
                ('total_reviews_completed', models.IntegerField(default=0)),
                ('total_ai_questions_used', models.IntegerField(default=0)),
                ('total_session_time_hours', models.FloatField(default=0.0)),
                ('days_active', models.IntegerField(default=0, help_text='Number of days user was active')),
                ('average_daily_reviews', models.FloatField(default=0.0)),
                ('feature_adoption_score', models.FloatField(default=0.0, help_text='Percentage of features used (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('upgrade_probability', models.FloatField(default=0.0, help_text='ML-calculated upgrade probability (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('churn_risk_score', models.FloatField(default=0.0, help_text='Risk of subscription cancellation (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_subscription_analytics',
                'ordering': ['-tier_start_date'],
                'indexes': [models.Index(fields=['user', 'tier_start_date'], name='bi_subscrip_user_id_bc6d52_idx'), models.Index(fields=['subscription_tier', 'is_active'], name='bi_subscrip_subscri_7c258b_idx'), models.Index(fields=['upgrade_probability'], name='bi_subscrip_upgrade_107573_idx'), models.Index(fields=['churn_risk_score'], name='bi_subscrip_churn_r_6f3cde_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('contents_created', models.IntegerField(default=0, help_text='Contents created today')),
                ('reviews_completed', models.IntegerField(default=0, help_text='Reviews completed today')),
                ('ai_questions_generated', models.IntegerField(default=0, help_text='AI questions generated today')),
                ('session_duration_minutes', models.IntegerField(default=0, help_text='Total session time in minutes')),
                ('success_rate', models.FloatField(default=0.0, help_text='Daily success rate percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_review_time_seconds', models.IntegerField(default=0, help_text='Average time spent per review in seconds')),
                ('peak_activity_hour', models.IntegerField(blank=True, help_text='Hour of day with most activity (0-23)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('login_count', models.IntegerField(default=0, help_text='Number of logins today')),
                ('consecutive_days', models.IntegerField(default=0, help_text='Current learning streak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_learning_pattern',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='bi_learning_user_id_03cabb_idx'), models.Index(fields=['date', 'success_rate'], name='bi_learning_date_47b698_idx'), models.Index(fields=['consecutive_days'], name='bi_learning_consecu_322dfe_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
