# Generated by Django 4.2.16 on 2025-09-30 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('contents_created', models.IntegerField(default=0, help_text='Contents created today')),
                ('reviews_completed', models.IntegerField(default=0, help_text='Reviews completed today')),
                ('success_rate', models.FloatField(default=0.0, help_text='Daily success rate percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_c4a930_idx'), models.Index(fields=['date'], name='analytics_d_date_26c219_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
