# Generated by Django 4.2.16 on 2025-11-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyStats',
        ),
    ]
