# Generated by Django 4.2.16 on 2025-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailystats_alter_learningpattern_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystats',
            name='study_streak_days',
        ),
    ]
