# Generated by Django 4.2.16 on 2025-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklytest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
