# Generated by Django 4.2.16 on 2025-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_test', '0002_alter_weeklytest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytest',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('preparing', '준비중'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklytestquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', '객관식'), ('true_false', 'O/X')], default='multiple_choice', max_length=20),
        ),
    ]
