# Generated by Django 4.2.7 on 2025-07-23 07:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('memory_usage_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('disk_usage_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('db_connection_count', models.IntegerField(help_text='Number of active DB connections')),
                ('db_query_avg_time_ms', models.FloatField(help_text='Average query time in milliseconds')),
                ('cache_hit_rate_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cache_memory_usage_mb', models.FloatField(help_text='Cache memory usage in MB')),
                ('celery_workers_active', models.IntegerField(default=0)),
                ('redis_status', models.BooleanField(default=True)),
                ('postgres_status', models.BooleanField(default=True)),
                ('api_requests_per_minute', models.FloatField(default=0)),
                ('api_error_rate_percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('api_avg_response_time_ms', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'monitoring_system_health',
                'indexes': [models.Index(fields=['date', 'timestamp'], name='monitoring__date_5f57a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_requests_count', models.IntegerField(default=0)),
                ('content_created_count', models.IntegerField(default=0)),
                ('reviews_completed_count', models.IntegerField(default=0)),
                ('ai_questions_generated_count', models.IntegerField(default=0)),
                ('session_duration_minutes', models.IntegerField(default=0)),
                ('unique_endpoints_accessed', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('first_activity', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_user_activity',
                'indexes': [models.Index(fields=['date', 'user'], name='monitoring__date_803766_idx'), models.Index(fields=['api_requests_count', 'date'], name='monitoring__api_req_583bc5_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('WARNING', 'Warning')], max_length=10)),
                ('message', models.TextField(help_text='Error message')),
                ('exception_type', models.CharField(help_text='Exception class name', max_length=200)),
                ('traceback', models.TextField(blank=True, help_text='Full traceback')),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Sanitized request data')),
                ('resolved', models.BooleanField(default=False, help_text='Error has been resolved')),
                ('occurrences', models.IntegerField(default=1, help_text='Number of times this error occurred')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_error_log',
                'indexes': [models.Index(fields=['level', 'date'], name='monitoring__level_3a3a04_idx'), models.Index(fields=['exception_type', 'date'], name='monitoring__excepti_61dd2c_idx'), models.Index(fields=['endpoint', 'date'], name='monitoring__endpoin_3128f9_idx'), models.Index(fields=['resolved', 'date'], name='monitoring__resolve_235f3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatabaseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='Database table name', max_length=100)),
                ('operation_type', models.CharField(choices=[('SELECT', 'Select'), ('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('COUNT', 'Count')], max_length=20)),
                ('execution_time_ms', models.FloatField(help_text='Query execution time in milliseconds')),
                ('rows_affected', models.IntegerField(default=0, help_text='Number of rows affected')),
                ('query_hash', models.CharField(help_text='MD5 hash of normalized query', max_length=64)),
                ('is_slow_query', models.BooleanField(default=False, help_text='Query took longer than threshold')),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_database_metrics',
                'indexes': [models.Index(fields=['table_name', 'date'], name='monitoring__table_n_c37f06_idx'), models.Index(fields=['operation_type', 'date'], name='monitoring__operati_23c164_idx'), models.Index(fields=['is_slow_query', 'date'], name='monitoring__is_slow_f7fe38_idx'), models.Index(fields=['execution_time_ms', 'date'], name='monitoring__executi_86d034_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('method', models.CharField(help_text='HTTP method', max_length=10)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('query_count', models.IntegerField(default=0, help_text='Number of database queries')),
                ('cache_hits', models.IntegerField(default=0, help_text='Number of cache hits')),
                ('cache_misses', models.IntegerField(default=0, help_text='Number of cache misses')),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('response_size_bytes', models.IntegerField(default=0, help_text='Response size in bytes')),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_api_metrics',
                'indexes': [models.Index(fields=['endpoint', 'date'], name='monitoring__endpoin_ff7f29_idx'), models.Index(fields=['status_code', 'date'], name='monitoring__status__292f20_idx'), models.Index(fields=['response_time_ms', 'date'], name='monitoring__respons_294476_idx'), models.Index(fields=['user', 'date'], name='monitoring__user_id_a1c31c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI GPT')], default='anthropic', max_length=50)),
                ('model_name', models.CharField(help_text='AI model used', max_length=100)),
                ('operation_type', models.CharField(choices=[('question_generation', 'Question Generation'), ('answer_evaluation', 'Answer Evaluation'), ('content_analysis', 'Content Analysis'), ('chat', 'AI Chat')], max_length=50)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens consumed')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD', max_digits=10)),
                ('processing_time_ms', models.IntegerField(help_text='Processing time in milliseconds')),
                ('success', models.BooleanField(default=True, help_text='Operation completed successfully')),
                ('quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('content_id', models.IntegerField(blank=True, help_text='Related content ID', null=True)),
                ('subscription_tier', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_ai_metrics',
                'indexes': [models.Index(fields=['user', 'date'], name='monitoring__user_id_60fbeb_idx'), models.Index(fields=['operation_type', 'date'], name='monitoring__operati_f2950e_idx'), models.Index(fields=['service_provider', 'date'], name='monitoring__service_5aba10_idx'), models.Index(fields=['success', 'date'], name='monitoring__success_8d8275_idx')],
            },
        ),
    ]
