# Generated by Django 4.2.7 on 2025-08-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
    ]
