# Generated by Django 4.2.7 on 2025-09-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_create_alert_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_rule_id_a653c4_idx',
            old_name='alerts_alert_history_rule_triggered_idx',
        ),
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_trigger_17d1ca_idx',
            old_name='alerts_alert_history_triggered_resolved_idx',
        ),
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_slack_s_554dbe_idx',
            old_name='alerts_alert_history_slack_email_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='alerts_aler_is_acti_9ea5d0_idx',
            old_name='alerts_alert_rule_is_active_metric_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='alerts_aler_alert_t_5ba205_idx',
            old_name='alerts_alert_rule_alert_type_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='alerts_aler_created_665951_idx',
            old_name='alerts_alert_rule_created_at_idx',
        ),
    ]
