# Generated by Django 4.2.7 on 2025-08-14 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='플랜 이름', max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free (3일)'), ('basic', 'Basic (90일)'), ('pro', 'Pro (180일)')], help_text='구독 티어', max_length=20)),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe 월간 가격 ID', max_length=100, null=True)),
                ('stripe_price_id_yearly', models.CharField(blank=True, help_text='Stripe 연간 가격 ID', max_length=100, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='월간 가격', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, help_text='연간 가격', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='플랜 설명')),
                ('features', models.JSONField(default=list, help_text='플랜 기능 목록')),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=200, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], default='monthly', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='결제 금액', max_digits=10)),
                ('currency', models.CharField(default='KRW', help_text='통화', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(max_length=200, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('succeeded', '성공'), ('failed', '실패'), ('canceled', '취소'), ('refunded', '환불')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
