# Generated by Django manually for performance optimization

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        # ReviewSchedule indexes for common queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS review_schedule_user_next_review_idx ON review_reviewschedule(user_id, next_review_date);",
            reverse_sql="DROP INDEX IF EXISTS review_schedule_user_next_review_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS review_schedule_user_active_idx ON review_reviewschedule(user_id, is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS review_schedule_user_active_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS review_schedule_initial_review_idx ON review_reviewschedule(user_id, initial_review_completed) WHERE initial_review_completed = false;",
            reverse_sql="DROP INDEX IF EXISTS review_schedule_initial_review_idx;"
        ),
        
        # ReviewHistory indexes for analytics queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS review_history_user_reviewed_idx ON review_reviewhistory(user_id, review_date DESC);",
            reverse_sql="DROP INDEX IF EXISTS review_history_user_reviewed_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS review_history_content_result_idx ON review_reviewhistory(content_id, result);",
            reverse_sql="DROP INDEX IF EXISTS review_history_content_result_idx;"
        ),
    ]