# Generated by Django 4.2.7 on 2025-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewschedule',
            name='initial_review_completed',
            field=models.BooleanField(default=False, help_text='Whether the initial review has been completed'),
        ),
    ]
