# Generated by Django 4.2.7 on 2025-07-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_add_performance_indexes'),
        ('review', '0002_reviewschedule_initial_review_completed'),
    ]

    operations = [
    ]
