# Generated by Django 4.2.16 on 2025-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewhistory_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhistory',
            name='selected_choice',
            field=models.CharField(blank=True, help_text='User selected choice for multiple choice mode', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewhistory',
            name='user_title',
            field=models.CharField(blank=True, help_text='User guessed title for subjective mode', max_length=100),
        ),
    ]
