# Generated by Django 4.2.7 on 2025-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewhistory_created_at_reviewhistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewhistory',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='reviewhistory',
            index=models.Index(fields=['user', '-review_date'], name='review_history_user_date'),
        ),
        migrations.AddIndex(
            model_name='reviewhistory',
            index=models.Index(fields=['content', '-review_date'], name='review_history_content_date'),
        ),
        migrations.AddIndex(
            model_name='reviewhistory',
            index=models.Index(fields=['user', 'result', '-review_date'], name='review_hist_user_result'),
        ),
        migrations.AddIndex(
            model_name='reviewhistory',
            index=models.Index(fields=['-review_date'], name='review_history_date_only'),
        ),
        migrations.AddIndex(
            model_name='reviewschedule',
            index=models.Index(fields=['user', 'next_review_date', 'is_active'], name='review_sched_user_active'),
        ),
        migrations.AddIndex(
            model_name='reviewschedule',
            index=models.Index(fields=['next_review_date'], name='review_schedule_next_date'),
        ),
        migrations.AddIndex(
            model_name='reviewschedule',
            index=models.Index(fields=['user', 'is_active'], name='review_schedule_user_active'),
        ),
        migrations.AddConstraint(
            model_name='reviewhistory',
            constraint=models.CheckConstraint(check=models.Q(('time_spent__gte', 0), ('time_spent__isnull', True), _connector='OR'), name='review_history_time_spent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reviewschedule',
            constraint=models.CheckConstraint(check=models.Q(('interval_index__gte', 0)), name='review_schedule_interval_index_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reviewschedule',
            constraint=models.CheckConstraint(check=models.Q(('next_review_date__gte', models.F('created_at'))), name='review_schedule_next_date_after_creation', violation_error_message='Next review date must be after creation date'),
        ),
    ]
