# Generated by Django 4.2.16 on 2025-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewhistory_selected_choice_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewhistory',
            name='review_history_content_date',
        ),
        migrations.RemoveIndex(
            model_name='reviewhistory',
            name='review_hist_user_result',
        ),
        migrations.RemoveIndex(
            model_name='reviewhistory',
            name='review_history_date_only',
        ),
        migrations.AddIndex(
            model_name='reviewhistory',
            index=models.Index(fields=['user', 'result'], name='review_hist_user_result'),
        ),
    ]
